'use client';
import { WhatsAppButton } from './whatsapp-button';
import { useEffect, useState } from 'react';
import { Menu, MessageCircle, CalendarDays, ChevronDown, X } from 'lucide-react';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { navigation, hubs, presentationHref } from '@/config/site';
export function Brand() { return <a href="/" className="brand" aria-label="Fitness Personal • Vitta Hub — início"><img src="/brand/fitness-personal-transparent.svg" width="1680" height="630" alt="Fitness Personal — VITA HUB · Assessoria Esportiva"/></a>; }
export function Header() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);
  useEffect(() => { const update = () => setScrolled(window.scrollY > 30); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  return <><a className="skip-link" href="#principal">Pular para o conteúdo</a><header className={`site-header ${scrolled ? 'scrolled' : ''}`}><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Navegação principal"><a href="/vitta-hub/">VITTA HUB</a><DropdownMenu><DropdownMenuTrigger className="nav-trigger">Condomínios <ChevronDown size={12}/></DropdownMenuTrigger><DropdownMenuContent className="nav-dropdown" align="start"><DropdownMenuItem asChild><a href="/gestao-esportiva-condominios/">Gestão Esportiva para Condomínios</a></DropdownMenuItem>{hubs.map(h=><DropdownMenuItem asChild key={h.path}><a href={h.path}>{h.name}</a></DropdownMenuItem>)}<DropdownMenuItem asChild><a className="dropdown-cta" href={presentationHref}>Quero apresentar a VITTA HUB ao meu condomínio</a></DropdownMenuItem></DropdownMenuContent></DropdownMenu>{navigation.slice(1).map(([name,path])=><a key={path} href={path}>{name}</a>)}</nav><a className="button small header-cta" href={presentationHref}>Solicitar apresentação</a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="mobile-trigger" aria-label="Abrir menu"><Menu/></SheetTrigger><SheetContent className="mobile-panel" showCloseButton={false}><SheetTitle>Explore a VITTA HUB</SheetTitle><SheetDescription>Gestão, movimento e pessoas.</SheetDescription><SheetClose className="menu-close" aria-label="Fechar menu"><X/></SheetClose><nav aria-label="Navegação mobile"><a href="/vitta-hub/">VITTA HUB</a><a href="/gestao-esportiva-condominios/">Condomínios · Gestão Esportiva</a>{hubs.map(h=><a className="subnav" key={h.path} href={h.path}>{h.name}</a>)}{navigation.slice(1).map(([name,path])=><a key={path} href={path}>{name==='Consultoria'?'Consultoria Online':name==='E-Hub'?'E-Hub Nutrition':name}</a>)}<a href="/contato/">Contato</a></nav></SheetContent></Sheet></div></header><nav className="mobile-bottom" aria-label="Ações rápidas"><button onClick={()=>setOpen(true)}><Menu size={19}/>Menu</button><WhatsAppButton><MessageCircle size={19}/>WhatsApp</WhatsAppButton><a href={presentationHref}><CalendarDays size={19}/>Apresentação</a></nav></>;
}
