import {notFound} from 'next/navigation';
import {getArticle,publishedArticles,formatDate} from '@/lib/articles';
import {metadataFor} from '@/lib/seo';
import {siteConfig} from '@/config/site';
import {FAQAccordion} from '@/components/pages/faq';
import {ArticleCard} from '@/components/content/article-card';
import {StructuredData} from '@/components/sections/structured-data';
export const dynamicParams=false;
export function generateStaticParams(){return publishedArticles().map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const article=getArticle(slug);if(!article)return {title:'Conteúdo não encontrado',robots:{index:false,follow:false}};const base=metadataFor(article.seo.title,article.seo.description,article.seo.canonical||`/conteudos/${slug}/`);return {...base,openGraph:{...base.openGraph,type:'article',publishedTime:article.publishedAt,modifiedTime:article.updatedAt||article.publishedAt}};}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const a=getArticle(slug);if(!a)notFound();const related=publishedArticles().filter(item=>item.slug!==slug&&(a.related.includes(item.slug)||item.category===a.category)).slice(0,3);
 return <main id="principal"><article className="article-page container"><nav className="breadcrumb" aria-label="Caminho da página"><ol><li><a href="/">Início</a></li><li><a href="/conteudos/">Conteúdos</a></li><li aria-current="page">{a.title}</li></ol></nav><span className="eyebrow">{a.category}</span><h1>{a.title}</h1><div className="article-meta">Por {a.author.name}{a.author.role&&` · ${a.author.role}`}<br/><time dateTime={a.publishedAt}>{formatDate(a.publishedAt)}</time>{a.updatedAt&&<> · Atualizado em <time dateTime={a.updatedAt}>{formatDate(a.updatedAt)}</time></>}</div><p className="page-lead">{a.excerpt}</p><img className="article-hero" src={a.image.src} alt={a.image.alt} width={a.image.width} height={a.image.height} fetchPriority="high"/><div className="article-body">{a.blocks.map((block,i)=>block.type==='paragraph'?<p key={i}>{block.text}</p>:block.type==='heading'?block.level===2?<h2 key={block.id} id={block.id}>{block.text}</h2>:<h3 key={block.id} id={block.id}>{block.text}</h3>:block.type==='list'?<ul key={i}>{block.items.map(item=><li key={item}>{item}</li>)}</ul>:<a className="text-link" key={i} href={block.href}>{block.label}</a>)}</div>{a.faq.length>0&&<section className="article-faq"><h2>Perguntas frequentes</h2><FAQAccordion items={a.faq}/></section>}<div className="article-next"><h2>Continue colocando conhecimento em movimento.</h2><a className="button" href={a.cta.href}>{a.cta.label}</a></div>{siteConfig.url&&<StructuredData data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.excerpt,datePublished:a.publishedAt,dateModified:a.updatedAt||a.publishedAt,author:{'@type':'Person',name:a.author.name},image:`${siteConfig.url}${a.image.src}`,mainEntityOfPage:`${siteConfig.url}/conteudos/${slug}/`,publisher:{'@type':'Organization',name:siteConfig.name}}}/>}</article>{related.length>0&&<section className="section container"><h2>Leituras relacionadas</h2><div className="articles-grid">{related.map(article=><ArticleCard key={article.slug} article={article}/>)}</div></section>}</main>;
}
