import { HubVisual } from '@/components/sections/ecosystem-visuals';
import { hubDetails, type HubSlug } from '@/content/pages';
import { PageHero, ContentSection, FeatureList, PageCTA, FAQSection } from './shared';
import { CTA } from '@/components/sections/ui';
import { hubs } from '@/config/site';
export function HubPage({slug}:{slug:HubSlug}) {
  const hub=hubDetails[slug];
  return <><PageHero slug={slug} eyebrow={hub.eyebrow} lead={hub.lead} cta="Conhecer a Gestão" href="/gestao-esportiva-condominios/" visual={<HubVisual slug={slug}/>}><p>{hub.description}</p></PageHero>
  <ContentSection label="Atividades e possibilidades" title={hub.introTitle}><div className="editorial-split"><p className="large-copy">{hub.intro}</p><FeatureList items={hub.activities}/></div><p className="fine-print">A composição das atividades e da programação depende do projeto do condomínio.</p></ContentSection>
  <ContentSection label={slug==='hub-esportivo'?'FutCross':'Metodologia e acompanhamento'} title={hub.featureTitle} tone="soft-section"><div className="editorial-split"><p className="large-copy">{hub.feature}</p><div>{slug==='hub-fitness'?<><h3>Autonomia e desempenho, conforme o objetivo.</h3><p><strong>T.A.L.</strong> — Treinamento para Autonomia e Longevidade: consciência corporal, CORE, mobilidade e o básico bem executado.</p><p><strong>T.A.R.</strong> — Treinamento de Alto Rendimento: força, potência, velocidade, condicionamento e preparação física.</p></>:slug==='hub-esportivo'?<div className="futcross-system"><span>Futebol</span><b>+</b><span>Movimento</span><b>+</b><span>Cognição</span></div>:<FeatureList items={['Profissionais e horários conectados','Programação conforme os níveis','Comunicação e acompanhamento','Experiência integrada à gestão']}/>}<CTA secondary href="/miva/">Conhecer a M.I.V.A.</CTA></div></div></ContentSection>
  <ContentSection label="Diferentes perfis" title="O planejamento começa pelas pessoas."><div className="editorial-split"><div><p className="large-copy">Necessidades, objetivos e momentos de vida orientam a proposta de atividades.</p><p>O Hub faz parte da estrutura B2B da FITNESS PERSONAL • VITTA HUB. Profissionais, programação, comunicação e acompanhamento se conectam à gestão do condomínio.</p></div><FeatureList items={hub.groups}/></div></ContentSection>
  <section className="section connected-hubs"><div className="container"><span className="eyebrow">Dentro de uma mesma estrutura</span><h2>Conheça as outras conexões.</h2><div className="related-hubs">{hubs.filter(h=>h.path!==`/${slug}/`).map(h=><a key={h.path} href={h.path}><h3>{h.name}</h3><p>{h.text}</p><span className="text-link">Conhecer o Hub</span></a>)}</div></div></section>
  <ContentSection label="Experiência e convivência" title={slug==='hub-aquatico'?'Aprendizagem e bem-estar em diferentes fases da vida.':slug==='hub-esportivo'?'Desenvolvimento, família e comunidade.':'Orientação e continuidade para a rotina do morador.'}><div className="editorial-split"><div><h3>{slug==='hub-aquatico'?'Natação e hidroginástica':slug==='hub-esportivo'?'Movimento e interação':'Objetivos de treinamento'}</h3><p>{slug==='hub-aquatico'?'Natação: aprender, evoluir e aproveitar a água com orientação profissional. Hidroginástica: movimento, condicionamento, bem-estar e convivência.':slug==='hub-esportivo'?'Coordenação, padrões fundamentais, percepção, tomada de decisão, interação, cooperação, disciplina e criatividade compõem a proposta de desenvolvimento nas atividades.':'Força, condicionamento, hipertrofia, composição corporal, longevidade ativa e performance são objetivos que podem orientar a prescrição conforme o perfil da pessoa.'}</p></div><div><h3>{slug==='hub-esportivo'?'Encontros que fazem parte da vida do condomínio':'A gestão sustenta a experiência'}</h3><p>{slug==='hub-esportivo'?'Jogos dirigidos, desafios e eventos esportivos criam oportunidades de convivência para moradores e famílias. A programação integra a proposta do condomínio e a composição de sua operação.':'Organização de horários, orientação profissional, comunicação e acompanhamento se conectam para apoiar uma experiência consistente e o aproveitamento dos espaços.'}</p><p>A metodologia M.I.V.A. mantém saúde, mente, nutrição e felicidade / motivação conectadas à visão de movimento.</p></div></div></ContentSection>
  <FAQSection items={[
    {question:'Este Hub é uma empresa independente?',answer:'Não. É uma divisão operacional do B2B Condomínios, dentro da estrutura de Gestão Esportiva Integrada da FITNESS PERSONAL • VITTA HUB.'},
    {question:'Todas as atividades estão presentes em todos os condomínios?',answer:'A programação, os horários e a equipe são definidos conforme os espaços, as necessidades e o escopo de cada projeto.'},
    {question:'Como conhecer a proposta para meu condomínio?',answer:'A página de Gestão Esportiva apresenta a estrutura e a jornada de implantação. A solicitação de apresentação é o próximo passo comercial.'},
  ]}/>
  <PageCTA title="O próximo passo é conhecer a gestão." text="Entenda como este Hub pode integrar o ecossistema esportivo do seu condomínio." label="Conhecer a Gestão" href="/gestao-esportiva-condominios/" secondary={{label:'Solicitar apresentação',href:'/contato/?interesse=gestao-esportiva'}}/>
  </>;
}
