import { StructuredData } from '@/components/sections/structured-data';
import { PageHero, ContentSection, FeatureList, PageCTA, ManagementMark, FAQSection } from './shared';
import { Ecosystem } from '@/components/sections/home';
import { team } from '@/content/home';
import { CTA } from '@/components/sections/ui';
export function InstitutionalPage(){return <>
  <PageHero slug="vitta-hub" eyebrow="FITNESS PERSONAL / Nossa estrutura" lead="Colocar mais movimento na vida das pessoas." cta="Conhecer a Gestão" href="/gestao-esportiva-condominios/" visual={<ManagementMark/>}><p>A FITNESS PERSONAL • VITTA HUB é uma assessoria esportiva integrada que conecta gestão, movimento, saúde, esporte, tecnologia e bem-estar para transformar espaços e oportunidades em experiências de uma vida mais ativa.</p></PageHero>
  <Ecosystem label="O jeito VITTA HUB"/>
  <ContentSection label="Propósito e posicionamento" title="Transformar espaços em experiências integradas." tone="soft-section"><div className="editorial-split"><p className="large-copy">Transformar espaços e estruturas existentes em experiências integradas de saúde, esporte e bem-estar.</p><div><p>A FITNESS PERSONAL • VITTA HUB é uma assessoria esportiva integrada especializada na gestão de atividades físicas, esportivas e de bem-estar, que conecta profissionais, modalidades, metodologia, tecnologia e acompanhamento em uma única estrutura.</p><p>Nosso principal campo de atuação é a gestão esportiva para condomínios residenciais de médio e alto padrão.</p></div></div></ContentSection>
  <ContentSection label="Arquitetura do ecossistema" title="Uma marca principal. Uma estrutura integrada."><div className="brand-architecture"><strong>FITNESS PERSONAL</strong><span>VITTA HUB • ASSESSORIA ESPORTIVA</span><b>GESTÃO ESPORTIVA INTEGRADA</b><div><a href="/gestao-esportiva-condominios/"><h3>B2B Condomínios</h3><p>Principal atuação comercial.</p><small>Hub Fitness · Hub Aquático · Hub Esportivo</small></a><a href="/consultoria-online/"><h3>Consultoria Online</h3><p>Treinamento digital e híbrido.</p></a><a href="/e-hub-nutrition/"><h3>E-Hub Nutrition</h3><p>Atendimento nutricional, orientação e suplementação.</p></a></div><a className="architecture-method" href="/miva/">M.I.V.A. — metodologia transversal</a></div></ContentSection>
  <ContentSection label="Diferenciais" title="Nosso diferencial não é oferecer mais modalidades. É integrar melhor tudo aquilo que já faz parte da vida esportiva das pessoas." tone="soft-section"><FeatureList items={['Gestão Esportiva Integrada: organização, coordenação e governança','Hubs Especializados dentro da mesma gestão','M.I.V.A.: metodologia transversal','Jornada de Evolução e acompanhamento','Físico + Digital: espaço, aplicativo e orientação','Experiência Humana: acolhimento e proximidade','Ecossistema Integrado: B2B, Consultoria e E-Hub']}/></ContentSection>
  <ContentSection label="Identidade" title="Somos uma estrutura integrada de gestão esportiva."><div className="editorial-split"><p className="large-copy">Não somos apenas fornecedores de professores, academia em condomínio, empresa de personal trainers, plataforma de treinos ou loja de suplementos.</p><div><h3>Nossa promessa</h3><p>Entregar uma experiência esportiva integrada, organizada e humana, que transforme o movimento em parte da vida das pessoas.</p><CTA secondary href="/equipe/">Conhecer quem conecta essa estrutura</CTA></div></div></ContentSection>
  <ContentSection label="O que nos orienta" title="Pessoas, ética e conexão." tone="soft-section"><div className="editorial-split"><div><h3>Missão</h3><p>Proporcionar mudanças profundas e readequação para o bem-estar físico e corporal através do conhecimento e da conscientização física, despertando o autoconhecimento e estimulando uma vida em movimento que eleve a autoestima e o prazer pela prática esportiva.</p><h3>Visão</h3><p>Ser a assessoria esportiva condominial de referência na Grande São Paulo, reconhecida pela eficiência prática de sua metodologia integrada (corpo, mente, nutrição e felicidade) e pela excelência em gestão operacional.</p></div><div><h3>Valores</h3><FeatureList items={['Valorização do Ser Humano','Ética e Honestidade','Respeito e Segurança','Conexão em Comunidade']}/></div></div></ContentSection>
  <section className="section manifesto"><div className="container"><span className="eyebrow">Nossa essência</span><h2>Criamos estruturas que conectam pessoas ao movimento e transformam espaços em experiências de saúde, esporte e bem-estar.</h2><p>Estratégica na gestão. Humana no relacionamento. Ativa na atitude. Profissional no conhecimento. Contemporânea na experiência.</p></div></section>
  <PageCTA title="Conheça a gestão por trás da experiência." text="Descubra como a VITTA HUB conecta o ecossistema esportivo do condomínio." label="Conhecer a Gestão" href="/gestao-esportiva-condominios/"/>
</>}
export function TeamPage(){return <><StructuredData data={{'@context':'https://schema.org','@graph':team.map(person=>({'@type':'Person',name:person.name,jobTitle:person.role,worksFor:{'@type':'Organization',name:'FITNESS PERSONAL • VITTA HUB'}}))}}/>
  <PageHero slug="equipe" eyebrow="Pessoas / Lideranças e responsabilidades" lead="Uma estrutura que integra direção, relacionamento, operação e acompanhamento." cta="Conhecer a VITTA HUB" href="/vitta-hub/"><p>Estas são as lideranças de referência da FITNESS PERSONAL • VITTA HUB. A composição da equipe operacional pode variar conforme cada condomínio e projeto.</p></PageHero>
  <section className="section container"><div className="leadership-list">{team.map((person,index)=><article key={person.name}><span className="leadership-initials" aria-hidden="true">{person.initials}</span><div><span className="eyebrow">Liderança / 0{index+1}</span><h2>{person.name}</h2><strong>{person.role}</strong><p>{person.text}</p></div></article>)}</div></section>
  <ContentSection label="Como a estrutura se conecta" title="Gestão, atendimento e operação na mesma direção." tone="soft-section"><div className="team-connections"><div><h3>Direção</h3><p>Governança, direção técnica, negociação e desenvolvimento da estrutura.</p></div><div><h3>Customer Success</h3><p>Onboarding, acolhimento, relacionamento e suporte à experiência.</p></div><div><h3>Hubs operacionais</h3><p>Fitness, Aquático e Esportivo integrados à programação e à gestão B2B.</p></div><div><h3>Nutrição</h3><p>Consultas, orientação, acompanhamento e curadoria nutricional.</p></div></div></ContentSection>
  <ContentSection label="Equipe operacional" title="A composição acompanha o projeto."><div className="editorial-split"><p className="large-copy">As lideranças não representam necessariamente toda a operação. Outros profissionais podem compor a equipe conforme o contrato e as necessidades de cada condomínio.</p><p>Acolhimento, organização, acompanhamento e orientação profissional conectam as diferentes áreas da VITTA HUB.</p></div></ContentSection>
  <FAQSection items={[{question:'Essas cinco pessoas são toda a equipe?',answer:'Não. São as lideranças e referências apresentadas no projeto. A equipe operacional pode incluir outros profissionais conforme cada condomínio e contrato.'},{question:'Como os Hubs se relacionam com a direção?',answer:'Fitness, Aquático e Esportivo são divisões operacionais da gestão B2B, conectadas à direção, à programação, à metodologia e ao acompanhamento da estrutura.'}]}/>
  <PageCTA title="Conheça a estrutura que conecta essas pessoas." text="Entenda a atuação da FITNESS PERSONAL • VITTA HUB e seu ecossistema integrado." label="Conhecer a VITTA HUB" href="/vitta-hub/"/>
</>}
