import { PageHero, ContentSection, FeatureList, PageCTA, FAQSection, ManagementMark } from './shared';
import { Hubs, Experience } from '@/components/sections/home';
import { CTA } from '@/components/sections/ui';
import { managementFAQ } from '@/content/pages';
export function ManagementPage(){return <>
  <PageHero slug="gestao-esportiva-condominios" eyebrow="Gestão Esportiva Integrada / B2B" lead="Mais do que oferecer atividades. Estruturamos, conectamos e gerimos todo o ecossistema esportivo do seu condomínio." visual={<ManagementMark/>}/>
  <ContentSection label="O desafio" title="Os espaços já existem. A integração precisa acontecer."><div className="editorial-split"><p className="large-copy">Academia, piscina, quadra e lazer fazem parte do condomínio. O desafio está em conectar tudo isso à rotina de quem vive ali.</p><div><p>Pessoas, profissionais, horários e modalidades precisam funcionar em conjunto. Comunicação, acompanhamento e experiência também fazem parte dessa gestão.</p><FeatureList items={['Organizar a programação','Conectar profissionais e modalidades','Acompanhar a operação','Cuidar da comunicação com os moradores']}/></div></div></ContentSection>
  <ContentSection label="A solução" title="Uma estrutura para conectar todo o ecossistema." tone="soft-section"><div className="editorial-split"><div><p className="large-copy">Centralizamos a gestão esportiva e integramos treinamento, esporte, saúde, tecnologia e bem-estar em uma única estrutura.</p><p>A FITNESS PERSONAL • VITTA HUB é uma assessoria esportiva integrada. A gestão reúne os profissionais, as atividades, a metodologia e o acompanhamento da operação.</p><CTA secondary href="/vitta-hub/">Conhecer a VITTA HUB</CTA></div><div className="management-stack"><span>Espaços do condomínio</span><strong>Gestão + profissionais + metodologia</strong><span>Programação + tecnologia + comunicação</span><strong>Experiência + acompanhamento</strong></div></div></ContentSection>
  <Hubs label="Divisões operacionais B2B"/>
  <ContentSection label="Metodologia transversal" title="M.I.V.A. conecta a proposta de cuidado."><div className="editorial-split"><p className="large-copy">Movimento Inteligente para uma Vida Ativa: saúde, mente, nutrição e felicidade / motivação orientam a visão integrada da VITTA HUB.</p><div><p>As pessoas podem começar em pontos diferentes. A metodologia acompanha necessidades, objetivos e momentos, nos Hubs e nas experiências de treinamento.</p><CTA secondary href="/miva/">Entender a metodologia</CTA></div></div></ContentSection>
  <ContentSection label="Públicos e benefícios" title="Uma gestão. Diferentes pessoas e necessidades." tone="soft-section"><div className="editorial-split"><div><h3>Para quem vive o condomínio</h3><FeatureList items={['Crianças em experiências de movimento e esporte','Adultos que buscam uma rotina ativa','Pessoas que priorizam autonomia e longevidade','Praticantes e esportistas com diferentes objetivos']}/><p className="fine-print">A programação e os públicos atendidos são definidos conforme cada projeto.</p></div><div><h3>Para quem administra</h3><FeatureList items={['Mais organização','Melhor aproveitamento das áreas','Integração entre modalidades','Acompanhamento da operação','Experiência mais consistente','Gestão centralizada']}/></div></div></ContentSection>
  <ContentSection label="Da proposta à rotina" title="Implantação com contexto, acompanhamento e evolução."><ol className="implementation-steps">{[
    ['Diagnóstico','Entender os espaços, os públicos e as necessidades do condomínio.'],
    ['Planejamento','Organizar a proposta, a programação e a estrutura de atuação.'],
    ['Implementação','Preparar a operação e conectar os profissionais ao projeto.'],
    ['Operação','Colocar a programação e o acompanhamento em movimento.'],
    ['Acompanhamento','Acompanhar a rotina, a comunicação e a experiência.'],
    ['Evolução','Ajustar a proposta conforme o desenvolvimento do projeto.'],
  ].map(([title,text],index)=><li key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></ContentSection>
  <ContentSection label="Gestão para síndicos, administradoras e conselhos" title="Nosso diferencial não é oferecer mais modalidades. É integrar melhor tudo aquilo que já faz parte da vida esportiva das pessoas."><div className="editorial-split"><div><h3>Quando as atividades estão isoladas</h3><p>Profissionais, modalidades, horários e comunicação podem ficar distribuídos entre diferentes pontos de gestão.</p></div><div><h3>Na proposta de gestão integrada</h3><p>Uma estrutura conecta a programação, os profissionais, a metodologia e o acompanhamento, com organização para o condomínio e continuidade na experiência dos moradores.</p></div></div><p className="fine-print">Comparação conceitual da proposta de gestão, sem representar resultados de um condomínio específico.</p></ContentSection>
  <Experience label="Experiência VITTA HUB"/><FAQSection items={managementFAQ}/><PageCTA/>
</>}
