import { NutritionCare } from '@/components/sections/ecosystem-visuals';
import { PageHero, ContentSection, FeatureList, PageCTA, FAQSection } from './shared';
import { nutritionFAQ } from '@/content/pages';
import { CTA } from '@/components/sections/ui';
import { siteConfig } from '@/config/site';
export function NutritionPage(){return <>
  <PageHero slug="e-hub-nutrition" eyebrow="E-Hub Nutrition / Atendimento nutricional" lead="Não começamos pelo pote. Começamos pela pessoa." cta="Falar com o Nutricionista" href="/contato/?interesse=nutricao" visual={<NutritionCare/>}><p>Atendimento nutricional, orientação e suplementação integrados ao ecossistema VITTA HUB.</p></PageHero>
  <ContentSection label="A pessoa por trás do atendimento" title="Douglas Silva — Nutricionista"><div className="editorial-split"><div><p className="large-copy">Nutrição esportiva, consultas, planejamento alimentar, acompanhamento e curadoria nutricional.</p><p>O cuidado começa pela avaliação e pela orientação individualizada, considerando a rotina e sua integração com o treinamento.</p><CTA href="/contato/?interesse=nutricao">Falar com o Nutricionista</CTA></div><div className="professional-note"><span className="eyebrow">Formatos de atendimento</span><h3>Consultas online</h3><p>Atendimento presencial mediante agendamento e composição da operação.</p><span className="text-link"><a href="/equipe/">Conhecer a equipe VITTA HUB</a></span></div></div></ContentSection>
  <ContentSection label="Avaliação e acompanhamento" title="Orientação individualizada, conectada à vida real." tone="soft-section"><div className="editorial-split"><p className="large-copy">A experiência nutricional reúne avaliação, orientação alimentar e acompanhamento, com suporte a praticantes, esportistas e clientes da consultoria.</p><FeatureList items={['Avaliação da pessoa e de suas necessidades','Orientação alimentar individualizada','Planejamento nutricional','Acompanhamento','Integração com o treinamento']}/></div></ContentSection>
  <ContentSection label="Treinamento + nutrição" title="Conexões que acompanham sua rotina."><div className="editorial-split"><div><h3>Nutrição como pilar da M.I.V.A.</h3><p>Saúde, mente, nutrição e felicidade / motivação compõem a visão transversal da metodologia. O E-Hub conecta a orientação nutricional a essa experiência.</p><CTA secondary href="/miva/">Conhecer a metodologia</CTA></div><div><h3>Consultoria com acompanhamento nutricional</h3><p>Performance & Nutri e Executive VIP incluem nutrição. Conheça as composições e confirme o escopo com o atendimento.</p><CTA secondary href="/consultoria-online/">Conhecer as ofertas</CTA></div></div></ContentSection>
  <ContentSection label="Suplementação como complemento" title="A orientação vem antes da escolha." tone="soft-section"><div className="nutrition-flow"><span>Pessoa</span><span>Necessidade</span><span>Orientação</span><span>Treino + nutrição</span><span>Suplementação quando pertinente</span></div><div className="editorial-split"><p className="large-copy">A curadoria e a loja ampliam a experiência de atendimento. A suplementação é apresentada como uma extensão do cuidado individualizado.</p><div><h3>Curadoria nutricional</h3><p>Probiótica, whey, creatina, ômega 3 e kits fazem parte do universo de suplementação descrito para o E-Hub.</p><p>Conheça as opções na loja virtual existente quando o acesso estiver disponível.</p>{siteConfig.storeUrl?<CTA channel="store" href={siteConfig.storeUrl}>Acessar loja virtual</CTA>:<><button className="button" disabled aria-describedby="store-availability">Acessar loja virtual</button><p className="fine-print" id="store-availability">O acesso será disponibilizado em breve.</p></>}</div></div></ContentSection>
  <FAQSection items={nutritionFAQ}/><PageCTA title="O próximo passo começa por você." text="Converse sobre o atendimento nutricional e suas necessidades." label="Falar com o Nutricionista" href="/contato/?interesse=nutricao"/>
</>}
